CUDA_VISIBLE_DEVICES=1 python main.py \
--mode train \
--batch_size 4 \
--accumulate_grad_batches 32 \
--dataset movielens_data \
--data_dir data/ref/movielens \
--cans_num 20 \
--prompt_path ./prompt/movie.txt \
--rec_embed SASRec \
--llm_tuning lora \
--llm_path ../llama/models_hf/7B \
--rec_model_path ./rec_model/movielens.pt \
--ckpt_dir ./checkpoints/movielens/ \
--output_dir ./output/movielens/ \
--log_dir movielens_logs \
--lr_warmup_start_lr 2e-6 \
--lr 2e-4 \
--lr_decay_min_lr 2e-6 \
--max_epochs 5